services:
  - title: Same Page
    desc: A full-service production covering everything Pre to Post.
  - title: small footprint, big impact
    desc: "Taking the bloat out of commercial video production, we know how to work
      in the new landscape of content creation and filmmaking. Making visually
      striking films with just the right amount of ingredients. "
