backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: frojo/same-page-website
media_folder: "src/assets/img"
public_folder: "/assets/img"
logo_url: "/static/img/same_page_logo_colors.svg"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Portfolio"
    name: "portfolio"
    folder: "src/_collections/portfolio"
    create: true
    fields:
      - { label: "Title", name: "my_title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Video Embed", name: "video_embed", widget: "code" }
      - label: "Credits"
        name: "credits"
        widget: "list"
        fields: 
          - label: "Credit"
            name: "credit"
            widget: "object"
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Role', name: 'role', widget: 'string' }
      - label: "Stills"
        name: "stills"
        widget: "list"
        field: { label: "Still", name: "still", widget: "image" }
